// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PeerLog is an object representing the database table.
type PeerLog struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	PeerID    int       `boil:"peer_id" json:"peer_id" toml:"peer_id" yaml:"peer_id"`
	Field     string    `boil:"field" json:"field" toml:"field" yaml:"field"`
	Old       string    `boil:"old" json:"old" toml:"old" yaml:"old"`
	New       string    `boil:"new" json:"new" toml:"new" yaml:"new"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *peerLogR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L peerLogL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PeerLogColumns = struct {
	ID        string
	PeerID    string
	Field     string
	Old       string
	New       string
	CreatedAt string
}{
	ID:        "id",
	PeerID:    "peer_id",
	Field:     "field",
	Old:       "old",
	New:       "new",
	CreatedAt: "created_at",
}

var PeerLogTableColumns = struct {
	ID        string
	PeerID    string
	Field     string
	Old       string
	New       string
	CreatedAt string
}{
	ID:        "peer_logs.id",
	PeerID:    "peer_logs.peer_id",
	Field:     "peer_logs.field",
	Old:       "peer_logs.old",
	New:       "peer_logs.new",
	CreatedAt: "peer_logs.created_at",
}

// Generated where

var PeerLogWhere = struct {
	ID        whereHelperint
	PeerID    whereHelperint
	Field     whereHelperstring
	Old       whereHelperstring
	New       whereHelperstring
	CreatedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "\"peer_logs\".\"id\""},
	PeerID:    whereHelperint{field: "\"peer_logs\".\"peer_id\""},
	Field:     whereHelperstring{field: "\"peer_logs\".\"field\""},
	Old:       whereHelperstring{field: "\"peer_logs\".\"old\""},
	New:       whereHelperstring{field: "\"peer_logs\".\"new\""},
	CreatedAt: whereHelpertime_Time{field: "\"peer_logs\".\"created_at\""},
}

// PeerLogRels is where relationship names are stored.
var PeerLogRels = struct {
}{}

// peerLogR is where relationships are stored.
type peerLogR struct {
}

// NewStruct creates a new relationship struct
func (*peerLogR) NewStruct() *peerLogR {
	return &peerLogR{}
}

// peerLogL is where Load methods for each relationship are stored.
type peerLogL struct{}

var (
	peerLogAllColumns            = []string{"id", "peer_id", "field", "old", "new", "created_at"}
	peerLogColumnsWithoutDefault = []string{"peer_id", "field", "old", "new", "created_at"}
	peerLogColumnsWithDefault    = []string{"id"}
	peerLogPrimaryKeyColumns     = []string{"id", "created_at"}
	peerLogGeneratedColumns      = []string{"id"}
)

type (
	// PeerLogSlice is an alias for a slice of pointers to PeerLog.
	// This should almost always be used instead of []PeerLog.
	PeerLogSlice []*PeerLog
	// PeerLogHook is the signature for custom PeerLog hook methods
	PeerLogHook func(context.Context, boil.ContextExecutor, *PeerLog) error

	peerLogQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	peerLogType                 = reflect.TypeOf(&PeerLog{})
	peerLogMapping              = queries.MakeStructMapping(peerLogType)
	peerLogPrimaryKeyMapping, _ = queries.BindMapping(peerLogType, peerLogMapping, peerLogPrimaryKeyColumns)
	peerLogInsertCacheMut       sync.RWMutex
	peerLogInsertCache          = make(map[string]insertCache)
	peerLogUpdateCacheMut       sync.RWMutex
	peerLogUpdateCache          = make(map[string]updateCache)
	peerLogUpsertCacheMut       sync.RWMutex
	peerLogUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var peerLogAfterSelectHooks []PeerLogHook

var peerLogBeforeInsertHooks []PeerLogHook
var peerLogAfterInsertHooks []PeerLogHook

var peerLogBeforeUpdateHooks []PeerLogHook
var peerLogAfterUpdateHooks []PeerLogHook

var peerLogBeforeDeleteHooks []PeerLogHook
var peerLogAfterDeleteHooks []PeerLogHook

var peerLogBeforeUpsertHooks []PeerLogHook
var peerLogAfterUpsertHooks []PeerLogHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PeerLog) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range peerLogAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PeerLog) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range peerLogBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PeerLog) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range peerLogAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PeerLog) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range peerLogBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PeerLog) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range peerLogAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PeerLog) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range peerLogBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PeerLog) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range peerLogAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PeerLog) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range peerLogBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PeerLog) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range peerLogAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPeerLogHook registers your hook function for all future operations.
func AddPeerLogHook(hookPoint boil.HookPoint, peerLogHook PeerLogHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		peerLogAfterSelectHooks = append(peerLogAfterSelectHooks, peerLogHook)
	case boil.BeforeInsertHook:
		peerLogBeforeInsertHooks = append(peerLogBeforeInsertHooks, peerLogHook)
	case boil.AfterInsertHook:
		peerLogAfterInsertHooks = append(peerLogAfterInsertHooks, peerLogHook)
	case boil.BeforeUpdateHook:
		peerLogBeforeUpdateHooks = append(peerLogBeforeUpdateHooks, peerLogHook)
	case boil.AfterUpdateHook:
		peerLogAfterUpdateHooks = append(peerLogAfterUpdateHooks, peerLogHook)
	case boil.BeforeDeleteHook:
		peerLogBeforeDeleteHooks = append(peerLogBeforeDeleteHooks, peerLogHook)
	case boil.AfterDeleteHook:
		peerLogAfterDeleteHooks = append(peerLogAfterDeleteHooks, peerLogHook)
	case boil.BeforeUpsertHook:
		peerLogBeforeUpsertHooks = append(peerLogBeforeUpsertHooks, peerLogHook)
	case boil.AfterUpsertHook:
		peerLogAfterUpsertHooks = append(peerLogAfterUpsertHooks, peerLogHook)
	}
}

// One returns a single peerLog record from the query.
func (q peerLogQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PeerLog, error) {
	o := &PeerLog{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for peer_logs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PeerLog records from the query.
func (q peerLogQuery) All(ctx context.Context, exec boil.ContextExecutor) (PeerLogSlice, error) {
	var o []*PeerLog

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PeerLog slice")
	}

	if len(peerLogAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PeerLog records in the query.
func (q peerLogQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count peer_logs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q peerLogQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if peer_logs exists")
	}

	return count > 0, nil
}

// PeerLogs retrieves all the records using an executor.
func PeerLogs(mods ...qm.QueryMod) peerLogQuery {
	mods = append(mods, qm.From("\"peer_logs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"peer_logs\".*"})
	}

	return peerLogQuery{q}
}

// FindPeerLog retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPeerLog(ctx context.Context, exec boil.ContextExecutor, iD int, createdAt time.Time, selectCols ...string) (*PeerLog, error) {
	peerLogObj := &PeerLog{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"peer_logs\" where \"id\"=$1 AND \"created_at\"=$2", sel,
	)

	q := queries.Raw(query, iD, createdAt)

	err := q.Bind(ctx, exec, peerLogObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from peer_logs")
	}

	if err = peerLogObj.doAfterSelectHooks(ctx, exec); err != nil {
		return peerLogObj, err
	}

	return peerLogObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PeerLog) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no peer_logs provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(peerLogColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	peerLogInsertCacheMut.RLock()
	cache, cached := peerLogInsertCache[key]
	peerLogInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			peerLogAllColumns,
			peerLogColumnsWithDefault,
			peerLogColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, peerLogGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(peerLogType, peerLogMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(peerLogType, peerLogMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"peer_logs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"peer_logs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into peer_logs")
	}

	if !cached {
		peerLogInsertCacheMut.Lock()
		peerLogInsertCache[key] = cache
		peerLogInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PeerLog.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PeerLog) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	peerLogUpdateCacheMut.RLock()
	cache, cached := peerLogUpdateCache[key]
	peerLogUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			peerLogAllColumns,
			peerLogPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, peerLogGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update peer_logs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"peer_logs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, peerLogPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(peerLogType, peerLogMapping, append(wl, peerLogPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update peer_logs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for peer_logs")
	}

	if !cached {
		peerLogUpdateCacheMut.Lock()
		peerLogUpdateCache[key] = cache
		peerLogUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q peerLogQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for peer_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for peer_logs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PeerLogSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), peerLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"peer_logs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, peerLogPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in peerLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all peerLog")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PeerLog) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no peer_logs provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(peerLogColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	peerLogUpsertCacheMut.RLock()
	cache, cached := peerLogUpsertCache[key]
	peerLogUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			peerLogAllColumns,
			peerLogColumnsWithDefault,
			peerLogColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			peerLogAllColumns,
			peerLogPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, peerLogGeneratedColumns)
		update = strmangle.SetComplement(update, peerLogGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert peer_logs, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(peerLogPrimaryKeyColumns))
			copy(conflict, peerLogPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"peer_logs\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(peerLogType, peerLogMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(peerLogType, peerLogMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert peer_logs")
	}

	if !cached {
		peerLogUpsertCacheMut.Lock()
		peerLogUpsertCache[key] = cache
		peerLogUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PeerLog record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PeerLog) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PeerLog provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), peerLogPrimaryKeyMapping)
	sql := "DELETE FROM \"peer_logs\" WHERE \"id\"=$1 AND \"created_at\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from peer_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for peer_logs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q peerLogQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no peerLogQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from peer_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for peer_logs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PeerLogSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(peerLogBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), peerLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"peer_logs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, peerLogPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from peerLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for peer_logs")
	}

	if len(peerLogAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PeerLog) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPeerLog(ctx, exec, o.ID, o.CreatedAt)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PeerLogSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PeerLogSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), peerLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"peer_logs\".* FROM \"peer_logs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, peerLogPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PeerLogSlice")
	}

	*o = slice

	return nil
}

// PeerLogExists checks if the PeerLog row exists.
func PeerLogExists(ctx context.Context, exec boil.ContextExecutor, iD int, createdAt time.Time) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"peer_logs\" where \"id\"=$1 AND \"created_at\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD, createdAt)
	}
	row := exec.QueryRowContext(ctx, sql, iD, createdAt)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if peer_logs exists")
	}

	return exists, nil
}

// Exists checks if the PeerLog row exists.
func (o *PeerLog) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PeerLogExists(ctx, exec, o.ID, o.CreatedAt)
}
