{
 "title": "IPFS Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Online Peers (last crawl)",
   "type": "stat",
   "description": "To how many peers could we connect to during the last crawl.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finished_at AS \"time\",\n  dialable_peers\nFROM crawls\nWHERE\n  $__timeFilter(finished_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Online Peers (now)",
   "type": "stat",
   "description": "Peers will leave the network in between crawls. This is the most recent and accurate approximation of dialable peers. This number is lower than the other one.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) AS \"id\" FROM sessions WHERE finished = 'false';"
    }
   ]
  },
  {
   "title": "Offline Peers (last crawl)",
   "type": "stat",
   "description": "This panel answers the question: How many peers did we find in the DHT but could not connect to?",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finished_at AS \"time\",\n  undialable_peers\nFROM crawls\nWHERE\n  $__timeFilter(finished_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Peers to dial in the next minute",
   "type": "stat",
   "description": "In the next minute the monitoring (not crawling) process will dial this number of peers.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,48h),\n  count(id) AS \"id\"\nFROM sessions\nWHERE\n  next_dial_attempt < NOW()+'1m'::interval\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "go-ipfs Agent Version Distribution",
   "type": "piechart",
   "description": "Distribution of agent versions that match roughly \"/go-ipfs/*/*\" while the middle part is summed up and displayed here.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cp.updated_at AS \"time\",\n  count AS \" \",\n  value\nFROM crawl_properties cp INNER JOIN properties p ON cp.property_id = p.id\nWHERE\n  $__timeFilter(cp.updated_at) AND\n  property = 'agent_version_core'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Complete Agent Version Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cp.updated_at AS \"time\",\n  value,\n  count AS \" \"\nFROM crawl_properties cp INNER JOIN properties p ON cp.property_id = p.id\nWHERE\n  $__timeFilter(cp.updated_at) AND\n  property = 'agent_version' AND\n  count >= 100 AND\n  value != '' AND\n  crawl_id = (SELECT id from crawls where state='succeeded' order by created_at desc limit 1)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(cp.updated_at,$__interval),\n  sum(count) AS \"other\"\nFROM crawl_properties cp INNER JOIN properties p ON cp.property_id = p.id\nWHERE\n  $__timeFilter(cp.updated_at) AND\n  property = 'agent_version' AND\n  count < 100 AND\n  crawl_id = (SELECT id from crawls where state='succeeded' order by created_at desc limit 1)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  cp.updated_at AS \"time\",\n  value,\n  count AS \" \"\nFROM crawl_properties cp INNER JOIN properties p ON cp.property_id = p.id\nWHERE\n  $__timeFilter(cp.updated_at) AND\n  property = 'agent_version' AND\n  value = '' AND\n  crawl_id = (SELECT id from crawls where state='succeeded' order by created_at desc limit 1)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Connection errors (last crawl)",
   "type": "piechart",
   "description": "The distribution of connection errors that happened in the last crawl. 'unknown' means that there is no dedicated label for it yet.",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cp.updated_at AS \"time\",\n  count AS \" \",\n  value\nFROM crawl_properties cp INNER JOIN properties p ON cp.property_id = p.id\nWHERE\n  $__timeFilter(cp.updated_at) AND\n  property = 'error'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Crawl Results",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  finished_at AS \"time\",\n  crawled_peers AS \"Total Peers\",\n  dialable_peers AS \"Dialable Peers\",\n  undialable_peers AS \"Undialable Peers\"\nFROM crawls\nWHERE\n  $__timeFilter(finished_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Supported Protocols (count >= 200)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  cp.updated_at AS \"time\",\n  count AS \" \",\n  value\nFROM crawl_properties cp INNER JOIN properties p ON cp.property_id = p.id\nWHERE\n  $__timeFilter(cp.updated_at) AND\n  property = 'protocol' AND\n  count > 200\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Percentage Dialable Peers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  finished_at AS \"time\",\n  cast(dialable_peers as decimal)/cast(crawled_peers as decimal) AS \"Ratio Dialable Peers\"\nFROM crawls\nWHERE\n  $__timeFilter(finished_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Peers in dial queue",
   "type": "timeseries",
   "description": "The length of the queue of peers that need to be dialed from the monitoring process.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "nebula_peers_to_dial_count{instance=\"localhost:6667\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Dial statistics in events/s",
   "type": "timeseries",
   "description": "How many peers does the monitoring process dial per second?\nHow many errors do occur per second?",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "rate(nebula_monitor_dials_count{instance=\"localhost:6667\"}[5m])",
     "legendFormat": "Dials"
    },
    {
     "expr": "rate(nebula_monitor_dial_errors_count{instance=\"localhost:6667\"}[5m])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Dial errors per second",
   "type": "timeseries",
   "description": "Which type of errors do occur per second?",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "rate(nebula_peers_to_dial_errors_count{instance=\"localhost:6667\"}[5m])",
     "legendFormat": "{{ error }}"
    }
   ]
  },
  {
   "title": "Agent Versions (count > 10)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  cp.updated_at AS \"time\",\n  count AS \" \",\n  left(value, 35)\nFROM crawl_properties cp INNER JOIN properties p ON cp.property_id = p.id\nWHERE\n  $__timeFilter(cp.updated_at) AND\n  property LIKE 'agent_version%' AND\n  value NOT LIKE '%go-ipfs%' AND\n  count > 10\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Agent Versions (count <= 10)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  cp.updated_at AS \"time\",\n  count AS \" \",\n  left(value, 35)\nFROM crawl_properties cp INNER JOIN properties p ON cp.property_id = p.id\nWHERE\n  $__timeFilter(cp.updated_at) AND\n  property LIKE 'agent_version%' AND\n  value NOT LIKE '%go-ipfs%' AND\n  count <= 10\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Crawl errors",
   "type": "timeseries",
   "description": "The distribution of errors that happened during a crawl.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  cp.updated_at AS \"time\",\n  count AS \" \",\n  p.value\nFROM crawl_properties cp INNER JOIN properties p ON cp.property_id = p.id\nWHERE\n  $__timeFilter(cp.updated_at) AND\n  p.property = 'error'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Supported Protocols (count <= 200)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  cp.updated_at AS \"time\",\n  count AS \" \",\n  value\nFROM crawl_properties cp INNER JOIN properties p ON cp.property_id = p.id\nWHERE\n  $__timeFilter(cp.updated_at) AND\n  property = 'protocol' AND\n  count <= 200\nORDER BY 1"
    }
   ]
  },
  { "title": "Continuous Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Individual Crawls",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "nebula_peers_to_crawl_count{instance=\"localhost:6666\"}",
     "legendFormat": "Peers to crawl"
    },
    {
     "expr": "sum(nebula_crawled_peers_count{instance=\"localhost:6666\"})",
     "legendFormat": "Peers crawled"
    }
   ]
  },
  {
   "title": "Total ever observed Peer IDs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) AS \"id\" FROM peers"
    }
   ]
  },
  {
   "title": "Total Peer IDs starting with Qm...",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM peers\nWHERE\n  multi_hash LIKE 'Qm%'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Crawl durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  EXTRACT(EPOCH FROM finished_at - started_at) as \"duration\"\nFROM crawls\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Peer IDs starting with 12D3KooW...",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM peers\nWHERE\n  multi_hash LIKE '12%'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SQL Queries/Execs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(nebula_go_sql_client_calls{instance=~\"localhost:6666|localhost:6667\"}[1m])",
     "legendFormat": "{{job}} - {{go_sql_method}}"
    }
   ]
  },
  {
   "title": "Average session lengths",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,30m),\n  avg(EXTRACT(EPOCH FROM min_duration)) as \"Min session length\"\nFROM sessions\nWHERE\n  $__timeFilter(updated_at)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,30m),\n  avg(EXTRACT(EPOCH FROM max_duration)) as \"Max session length\"\nFROM sessions\nWHERE\n  $__timeFilter(updated_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sessions Lifecycle/30m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(first_failed_dial,30m),\n  count(id) AS \"Sessions ended\"\nFROM sessions\nWHERE\n  $__timeFilter(first_failed_dial)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,30m),\n  count(id) AS \"Sessions started\"\nFROM sessions\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}