version: "3.9"
services:
  nebula_monitor:
    image: dennistra/nebula-crawler:sha-ce5c756
    container_name: nebula_monitor
    restart: always
    user: nebula
    ports:
      - "6667:6667"
    command: ["nebula", "monitor"]
    environment:
      NEBULA_DATABASE_HOST: postgres
      NEBULA_DATABASE_PORT: 5432
      NEBULA_DATABASE_NAME: nebula
      NEBULA_DATABASE_USER: nebula
      NEBULA_DATABASE_PASSWORD: password # TODO: unsafe
      NEBULA_DATABASE_SSL_MODE: disable
      NEBULA_TELEMETRY_PORT: 6667
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      nebula:
  postgres:
    image: postgres:14
    container_name: nebula_db
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nebula"]
      interval: 10s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_PASSWORD: password # TODO: unsafe
      POSTGRES_USER: nebula
      POSTGRES_DB: nebula
    networks:
      nebula:
  prometheus:
    container_name: nebula_prometheus
    image: prom/prometheus:v2.40.2
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      nebula:
  grafana:
    container_name: nebula_grafana
    image: grafana/grafana:9.2.5
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      nebula:
networks:
  nebula:
    name: nebula
volumes:
  psql_data: {}
  prometheus_data: {}
  grafana_data: {}
