// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Crawls         string
	MultiAddresses string
	PeerProperties string
	Peers          string
}{
	Crawls:         "crawls",
	MultiAddresses: "multi_addresses",
	PeerProperties: "peer_properties",
	Peers:          "peers",
}
