// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Crawls                string
	MonitoringConnections string
	MonitoringPeers       string
	PeerProperties        string
	Peers                 string
	Sessions              string
}{
	Crawls:                "crawls",
	MonitoringConnections: "monitoring_connections",
	MonitoringPeers:       "monitoring_peers",
	PeerProperties:        "peer_properties",
	Peers:                 "peers",
	Sessions:              "sessions",
}
