// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AgentVersions        string
	CrawlProperties      string
	Crawls               string
	IPAddresses          string
	MultiAddresses       string
	Neighbors            string
	PeerLogs             string
	Peers                string
	PeersXMultiAddresses string
	Protocols            string
	ProtocolsSets        string
	Sessions             string
	SessionsClosed       string
	SessionsOpen         string
	Visits               string
}{
	AgentVersions:        "agent_versions",
	CrawlProperties:      "crawl_properties",
	Crawls:               "crawls",
	IPAddresses:          "ip_addresses",
	MultiAddresses:       "multi_addresses",
	Neighbors:            "neighbors",
	PeerLogs:             "peer_logs",
	Peers:                "peers",
	PeersXMultiAddresses: "peers_x_multi_addresses",
	Protocols:            "protocols",
	ProtocolsSets:        "protocols_sets",
	Sessions:             "sessions",
	SessionsClosed:       "sessions_closed",
	SessionsOpen:         "sessions_open",
	Visits:               "visits",
}
