// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Crawls", testCrawls)
	t.Run("MultiAddresses", testMultiAddresses)
	t.Run("PeerProperties", testPeerProperties)
	t.Run("Peers", testPeers)
}

func TestDelete(t *testing.T) {
	t.Run("Crawls", testCrawlsDelete)
	t.Run("MultiAddresses", testMultiAddressesDelete)
	t.Run("PeerProperties", testPeerPropertiesDelete)
	t.Run("Peers", testPeersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Crawls", testCrawlsQueryDeleteAll)
	t.Run("MultiAddresses", testMultiAddressesQueryDeleteAll)
	t.Run("PeerProperties", testPeerPropertiesQueryDeleteAll)
	t.Run("Peers", testPeersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Crawls", testCrawlsSliceDeleteAll)
	t.Run("MultiAddresses", testMultiAddressesSliceDeleteAll)
	t.Run("PeerProperties", testPeerPropertiesSliceDeleteAll)
	t.Run("Peers", testPeersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Crawls", testCrawlsExists)
	t.Run("MultiAddresses", testMultiAddressesExists)
	t.Run("PeerProperties", testPeerPropertiesExists)
	t.Run("Peers", testPeersExists)
}

func TestFind(t *testing.T) {
	t.Run("Crawls", testCrawlsFind)
	t.Run("MultiAddresses", testMultiAddressesFind)
	t.Run("PeerProperties", testPeerPropertiesFind)
	t.Run("Peers", testPeersFind)
}

func TestBind(t *testing.T) {
	t.Run("Crawls", testCrawlsBind)
	t.Run("MultiAddresses", testMultiAddressesBind)
	t.Run("PeerProperties", testPeerPropertiesBind)
	t.Run("Peers", testPeersBind)
}

func TestOne(t *testing.T) {
	t.Run("Crawls", testCrawlsOne)
	t.Run("MultiAddresses", testMultiAddressesOne)
	t.Run("PeerProperties", testPeerPropertiesOne)
	t.Run("Peers", testPeersOne)
}

func TestAll(t *testing.T) {
	t.Run("Crawls", testCrawlsAll)
	t.Run("MultiAddresses", testMultiAddressesAll)
	t.Run("PeerProperties", testPeerPropertiesAll)
	t.Run("Peers", testPeersAll)
}

func TestCount(t *testing.T) {
	t.Run("Crawls", testCrawlsCount)
	t.Run("MultiAddresses", testMultiAddressesCount)
	t.Run("PeerProperties", testPeerPropertiesCount)
	t.Run("Peers", testPeersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Crawls", testCrawlsHooks)
	t.Run("MultiAddresses", testMultiAddressesHooks)
	t.Run("PeerProperties", testPeerPropertiesHooks)
	t.Run("Peers", testPeersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Crawls", testCrawlsInsert)
	t.Run("Crawls", testCrawlsInsertWhitelist)
	t.Run("MultiAddresses", testMultiAddressesInsert)
	t.Run("MultiAddresses", testMultiAddressesInsertWhitelist)
	t.Run("PeerProperties", testPeerPropertiesInsert)
	t.Run("PeerProperties", testPeerPropertiesInsertWhitelist)
	t.Run("Peers", testPeersInsert)
	t.Run("Peers", testPeersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("MultiAddressToPeerUsingPeer", testMultiAddressToOnePeerUsingPeer)
	t.Run("PeerPropertyToCrawlUsingCrawl", testPeerPropertyToOneCrawlUsingCrawl)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {
	t.Run("PeerToMultiAddressUsingMultiAddress", testPeerOneToOneMultiAddressUsingMultiAddress)
}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("CrawlToPeerProperties", testCrawlToManyPeerProperties)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("MultiAddressToPeerUsingMultiAddress", testMultiAddressToOneSetOpPeerUsingPeer)
	t.Run("PeerPropertyToCrawlUsingPeerProperties", testPeerPropertyToOneSetOpCrawlUsingCrawl)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {
	t.Run("PeerToMultiAddressUsingMultiAddress", testPeerOneToOneSetOpMultiAddressUsingMultiAddress)
}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("CrawlToPeerProperties", testCrawlToManyAddOpPeerProperties)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Crawls", testCrawlsReload)
	t.Run("MultiAddresses", testMultiAddressesReload)
	t.Run("PeerProperties", testPeerPropertiesReload)
	t.Run("Peers", testPeersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Crawls", testCrawlsReloadAll)
	t.Run("MultiAddresses", testMultiAddressesReloadAll)
	t.Run("PeerProperties", testPeerPropertiesReloadAll)
	t.Run("Peers", testPeersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Crawls", testCrawlsSelect)
	t.Run("MultiAddresses", testMultiAddressesSelect)
	t.Run("PeerProperties", testPeerPropertiesSelect)
	t.Run("Peers", testPeersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Crawls", testCrawlsUpdate)
	t.Run("MultiAddresses", testMultiAddressesUpdate)
	t.Run("PeerProperties", testPeerPropertiesUpdate)
	t.Run("Peers", testPeersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Crawls", testCrawlsSliceUpdateAll)
	t.Run("MultiAddresses", testMultiAddressesSliceUpdateAll)
	t.Run("PeerProperties", testPeerPropertiesSliceUpdateAll)
	t.Run("Peers", testPeersSliceUpdateAll)
}
